---
- hosts: localhost

  tasks:

  - name: Ssh key generation
    openssh_keypair:
      mode: 0400
      size: 2048
      type: rsa
      comment: ssh_session_key
      path: "{{ ansible_ssh_private_key_file }}"
